name: its_shared
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # flutter_web_plugins:
  #   sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  # My private ui
  # rich_ui:
  #   git:
  #     url: https://github.com/ThabangMmusi/rich_ui
    # path: C:/SoftwareDevelopment/rich_ui/
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  # url_strategy: ^0.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.1.3
  flutter_svg: ^2.0.7
  flutter_dropzone: ^4.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.1
  file_selector: ^1.0.1
  url_launcher: ^6.2.1
  protocol_handler: ^0.2.0
  # http: ^1.1.0
  http: ^0.13.4
  clipboard: ^0.1.3
  bitsdojo_window: ^0.1.5
  desktop_window: ^0.4.0
  windows_single_instance: ^1.0.0
  pdf: ^3.10.6
  connectivity_plus: ^6.0.3
  firedart: ^0.9.8
  # cloudinary_public: ^0.23.1
  file_picker: ^8.0.5
  # firebase_app_check: ^0.3.0+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  timeago: ^3.7.0
  pdfx: ^2.6.0
  internet_file: ^1.2.0
  # cached_network_image: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

  fonts: 
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/poppins/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
