name: its_shared
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  # My private ui
  rich_ui:
    path: C:/SoftwareDevelopment/rich_ui/
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.1.3
  flutter_svg: ^2.0.7
  flutter_dropzone: ^4.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  file_selector: ^1.0.1
  url_launcher: ^6.2.1
  protocol_handler: ^0.2.0
  http: ^1.1.0
  clipboard: ^0.1.3
  bitsdojo_window: ^0.1.5
  desktop_window: ^0.4.0
  windows_single_instance: ^1.0.0
  pdf: ^3.10.6
  connectivity_plus: ^6.0.3
  firedart: ^0.9.8
  cloudinary_public: ^0.23.1
  file_picker: ^8.0.5
  firebase_app_check: ^0.3.0+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  # cached_network_image: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces_72pt-SemiBold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/scraps/AlfaSlabOne-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/scraps/Amiri-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/scraps/Caveat-Medium.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/scraps/Lato-Regular.ttf
    - family: Mali
      fonts:
        - asset: assets/fonts/scraps/Mali-Medium.ttf
    - family: PathwayGothicOne
      fonts:
        - asset: assets/fonts/scraps/PathwayGothicOne-Regular.ttf
