// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsQTEqU_9yvKvKuXhqv8NntPMEmo3SDsw',
    appId: '1:830312586949:web:2dd7224c44f7c301269aac',
    messagingSenderId: '830312586949',
    projectId: 'spushare-2023',
    authDomain: 'spushare-2023.firebaseapp.com',
    storageBucket: 'spushare-2023.appspot.com',
    measurementId: 'G-3WE3XSBMWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVt361KUEBiQp2Sl-md1g712wSiggvO4',
    appId: '1:830312586949:android:1ec90371334b1397269aac',
    messagingSenderId: '830312586949',
    projectId: 'spushare-2023',
    storageBucket: 'spushare-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9yuIHhxBWnEo1UyZbWPDt07ctBToyGk',
    appId: '1:830312586949:ios:590fe652e5f243a3269aac',
    messagingSenderId: '830312586949',
    projectId: 'spushare-2023',
    storageBucket: 'spushare-2023.appspot.com',
    androidClientId: '830312586949-30po7899i95jj82p5h5r4gra4oi5k69m.apps.googleusercontent.com',
    iosClientId: '830312586949-igs9r5kncjvb0ge13k39v2259o6imrem.apps.googleusercontent.com',
    iosBundleId: 'com.rva.itsshared',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj9yuIHhxBWnEo1UyZbWPDt07ctBToyGk',
    appId: '1:830312586949:ios:069d8f88f87a7441269aac',
    messagingSenderId: '830312586949',
    projectId: 'spushare-2023',
    storageBucket: 'spushare-2023.appspot.com',
    iosClientId:
        '830312586949-2452d4p2h0pguaa2a04hqdqqik37gqms.apps.googleusercontent.com',
    iosBundleId: 'com.example.spuShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsQTEqU_9yvKvKuXhqv8NntPMEmo3SDsw',
    appId: '1:830312586949:web:2dd7224c44f7c301269aac',
    messagingSenderId: '830312586949',
    projectId: 'spushare-2023',
    authDomain: 'spushare-2023.firebaseapp.com',
    storageBucket: 'spushare-2023.appspot.com',
    measurementId: 'G-3WE3XSBMWP',
  );

}